version: "3.4"

services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        restart: on-failure
        command: node index
        env_file:
            - .env
        volumes:
            - ./:/app:cached
        network_mode: "host"

